name: Build Container Image
on:
  push:
    branches:
      - 'master'
    tags:
      - v*

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/setup-buildx-action@v2.2.1

      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tagname
        id: tagname
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # ${{ github.ref }} will replaced by GitHub Actions
          # shellcheck disable=SC2193
          [[ "${{ github.ref }}" == refs/tags/* ]] && VERSION="${VERSION/v/}"
          [[ "$VERSION" == "master" ]] && VERSION=latest
          echo $VERSION
          echo ::set-output name=version::$VERSION

      - name: Build and Push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/yanorei32/discord-tts:${{ steps.tagname.outputs.version }}
