name: hadolint

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/hadolint.yml'

jobs:
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: hadolint
        uses: reviewdog/action-hadolint@v1.50.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
